install: composer install
language: php
php:
- 7.1
script:
- vendor/bin/phpcs --standard=PSR1,PSR2 Soneritics/PostNL/
- mkdir -p build/logs
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/Voormelding/
after_script:
  - php vendor/bin/coveralls -v
